### ISSUE TITLE
Windows Safe wallet v0.36.5 error when trying to export all private keys...

### ISSUE THREAD

**Issue by jpass022** [Fair-Exchange/safewallet#38]
<<<<<<< HEAD
This issue tracker is only for technical issues related to safecoind

General Safecoin questions and/or support requests and are best directed to Discord
This issue tracker is only for technical issues related to komodod

General Komodo questions and/or support requests and are best directed to Discord

c00e1b3... komodo 0.5.2

Describe the issue
error when trying to export all private keys in QT GUI...

Can you reliably reproduce the issue?
If so, please list the steps to reproduce below:
Start QT v0.36.5
select 'File' dropdown, top- left
select 'Export all private keys'
key list is not generated, get pop-up error instead
Expected behaviour
generate list of private keys

Actual behaviour + errors
Tell us what happens instead including any noticable error output (any messages displayed on-screen when e.g. a crash occurred)
![image](https://user-images.githubusercontent.com/5889788/89737020-80f5c880-da33-11ea-8af1-9e83c69723dc.png)

<<<<<<< HEAD

The version of Safecoin you were using:
Run safecoind --version to find out
SafeWallet v0.36.5, Aug 8 2020
The version of Komodo you were using:
Run komodod --version to find out

c00e1b3... komodo 0.5.2

Machine specs:
OS name + version: Win 10
CPU: Xeon
RAM: 64 GB
Disk size: 2 TB
Disk Type (HD/SDD): NVMe SSD

**Comment by Fair-Exchange** [comment]
This was due to an outdated safecoind daemon, however there Is a similar issue with private key export which has now been solved:
https://github.com/Fair-Exchange/safecoin/commit/27e5a99204b4b1fbd70d720789e1cc6c1623382e
https://github.com/Fair-Exchange/safecoin/commit/8ff34dd9de941ab0fe1c55b24320795ffd0dc41f
https://github.com/Fair-Exchange/safewallet/commit/fb07f35e7fcc709696d7510237dd1e5bb96ee3ad
https://github.com/Fair-Exchange/safewallet/commit/9a3bfaa246881efeb903dad2cc299dc13abe23e5
